env:
  global:
  - GH_USER: francisco-guilherme
  - GH_REPO: pentaho-angular-toolkit
  - secure: "CRwqa1zIxtYQ1OzsMk8/OMJLPoJ1gRkGV4bwwfTcV1/XLWTxGG2P+OddG5Ipz7TmloFMwl8U9oo+bMTATDS3sGrIQl3frhxEhR/aP5BwfQEEGkcKNVF8LD4IqZ9q6xhqKZeD4TEPZ9OqSpyMBi20DIqxVHsQbJ2oPc7Qv0BP7iZqPFF94ZxqeWhlFjX+W38OOH0Nf0qrLF56S/MCEBDlE0j4f14CSJ8xtNcwwX3Njs7b2lVJBUYH9p1kpn+FfsjTL7unyuWfqvkU6a7yKUOw7oekuRNlT0LDnxIBCowXLWnC+mjDSCcOFUYR42PU03ceJjH4aMTHa5c7nJay2XLu7HRROOxwl+cppHEhb+1YeSdJKWvTGhHdJuejk9YqS5GtzoLD6Rg1wX4qWalRBid9Xu42eyAPBX9HN3wmRSySs3qnN3ZFNswWdoyTTukiZgUgmSF9obL69jrYScVATv5HydnE1xZ8jWrS5taKh5rR7ymSc/Ycsg9FTbudaWK6BfAKbZVmxoVqynP8Kf76Xshav6w0j7+cwu00YTJKHaQABD+1z5O57LfMVchlwT5H1akyll8h7CIessVToUEf5zND34nvEZq+4e8OmG8up6n/6Ofl66TlAPLc+NgyxlzxVKDx6Cke/Dm1TG6pU5SCZ7JR28eBeqDZAMs1JlndV6+DYS0="

language: node_js
node_js:
- '0.10'

before_install:
- npm install -g npm@2

install:
- npm install -g gulp
- npm install -g jsdoc
- npm install

script:
- gulp

before_deploy:
- gulp release --version $TRAVIS_BRANCH
- cp -r module_dist $GH_REPO
- zip -r $GH_REPO-$TRAVIS_BRANCH.zip $GH_REPO -x *.git*

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $GH_REPO-$TRAVIS_BRANCH.zip
  on:
    tags: true
    repo: $GH_USER/$GH_REPO

after_deploy:
- bash _scripts/deploy-module.sh
- bash _scripts/deploy-doc.sh


