env:
  global:
  - GH_REPO: pentaho-angular-toolkit
  - secure: "aM9pqIpQA6lhKZkA+sT4pfRdNPJrFTXZdTEooGngDQW/AMOwrNQfmdB1DGvGg2uXbuKFg5SlJ4YJJf/mTXkFtEDzEuV84/OjNq/X8GbHeA/Xk1X1iIupwN4WcnIqeEQAJ4QfiQUPgVXgqvpFbfIKx+l3iINyrdttxNuNLnJ5v9frVC+NSUg4Hik3adgbYbAJDzZCI1NKQdEO9W6anuasw71I9sKwSPPwfGXvp2oEr2unnyccK0fCPDlL681hajVd8Daou1pQUSboJN5ANd7x6QQRmmGZ6Uc0UO1q0w7OilAZm3QzC5eMYY1g8I49OZjudenmI8BxAt8p7ymqYUN1ujwVvJ6u/aG4a+hqbqdpCOHfw4csmECnpOx5xY1QzvVE6kO+74uAADmF9vNOdIBfgHAM/EH5EwChiMvOyeKDeHg4n158gw1trpkFNtAGQyAcgLSGBaOb4Pcma58j7b6nX2DVQYgiMedD5UynRPDdFYibhf35UYKe29m3PhNbtsxqYlchDfTzNPpfMShz5Gkdd/ZayUBgONnQawNgaIuq4vO6AgxfFlEK8OmK9qgOF7BFcUjp5ubj+ofVKj15tVhk20zNPxw/f84w1qenRjs5KJkhsr2AhH2krdmFd3u0nke1lQAGvOruaYrMyuNddsRU5QLgPswLDneepcJuIRec+os="

language: node_js
node_js:
- '0.10'

before_install:
- npm install -g npm@2

install:
- npm install -g gulp
- npm install -g jsdoc
- npm install

script:
- gulp

before_deploy:
- gulp release --version $TRAVIS_TAG
- cp -r module_dist $GH_REPO
- zip -r $GH_REPO-$TRAVIS_TAG.zip $GH_REPO -x *.git*

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $GH_REPO-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: $TRAVIS_REPO_SLUG

after_deploy:
- bash _scripts/deploy-module.sh
- bash _scripts/deploy-doc.sh


