env:
  global:
  - GH_REPO: pentaho-angular-toolkit
  - secure: "Hza0I5dzrZM4iU137EzKV29TGxH07XUOM98pl4F/JrTuTWsevP14lr48tpCcLGy4d4oytp5Nvodo4g75HZYbw2VYBG4s6rtMXNIEhWTiA0whMyWIoS3J1AesBOkWMzfq/GgxcOju4LDOAxJpZ2NDySUzya8bhS6blmFmZ1rNCroni7G1E6DeEeXS5c6cia9K0CJ11iS2WvqyTKzpGYDPUgm+j3DbXNw0cNI+1PNveo78KQt7BLJSaSDfJDlz9i5v+aMj9hVxsBvIoY4kbdWfQwUUvHWY3RjVhGbLAxpbzemy8WwdFPn1CiCVbXJyIJCpCDO3T9OTlkNrLNbVlLvX/aH8Lm9INblO0grsbrUKOA3P7ws1Gq9wbdFy+8NvEo2XyiKNKGbj6l36R8pBF0BbBlXzJubro7UGereGoZJ0CwvsujdSI6K0z881NjqIgJv8fPDiV9qDR98ZRUX4Nv+jhqCdfokTGbrPbNPmJm0AKrIYmRNHYRxO7LJBK6mUkDZElX9SJ7lj0tglBBZ5MOGyAbldQ/SX28npHLKQRIQfzkKRvc3elwlOjyKhxFqCaqC1LjB0mA2lekECts3J2er2WoN1nDGrz2vh0WWr/di8IrHr4AXnCcknuiWUvqyjowfQxM2lN7g5QZ44FIBQ7Qul5y1dfijzY2V5itvmWyu4nfY="

language: node_js
node_js:
- '0.10'

before_install:
- npm install -g npm@2

install:
- npm install -g gulp
- npm install -g jsdoc
- npm install

script:
- gulp

before_deploy:
- gulp release --version $TRAVIS_TAG
- cp -r module_dist $GH_REPO
- zip -r $GH_REPO-$TRAVIS_TAG.zip $GH_REPO -x *.git*

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $GH_REPO-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: $TRAVIS_REPO_SLUG

after_deploy:
- bash _scripts/deploy-module.sh
- bash _scripts/deploy-doc.sh


